/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_main (void)
{
  GtkWidget *window_main;
  GtkWidget *vbox_main;
  GtkWidget *menubar;
  GtkWidget *menubar_file;
  GtkWidget *menubar_file_menu;
  GtkWidget *login;
  GtkWidget *image336;
  GtkWidget *logout;
  GtkWidget *image337;
  GtkWidget *file_separator_one;
  GtkWidget *restart;
  GtkWidget *image338;
  GtkWidget *shutdown;
  GtkWidget *image339;
  GtkWidget *file_separator_two;
  GtkWidget *quit;
  GtkWidget *image340;
  GtkWidget *menubar_process;
  GtkWidget *menubar_process_menu;
  GSList *process_update_three_group = NULL;
  GtkWidget *process_update_three;
  GtkWidget *process_update_five;
  GtkWidget *separator_one;
  GtkWidget *process_kill;
  GtkWidget *image341;
  GtkWidget *menubar_fview;
  GtkWidget *menubar_fview_menu;
  GtkWidget *fview_rename;
  GtkWidget *image342;
  GtkWidget *fview_delete;
  GtkWidget *image343;
  GtkWidget *edit_separator_one;
  GtkWidget *fview_upload;
  GtkWidget *image344;
  GtkWidget *fview_downolad;
  GtkWidget *image345;
  GtkWidget *menubar_help;
  GtkWidget *menubar_help_menu;
  GtkWidget *help_topic;
  GtkWidget *image346;
  GtkWidget *help_separator_one;
  GtkWidget *help_about;
  GtkWidget *image347;
  GtkWidget *toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolitem_back;
  GtkWidget *button_back;
  GtkWidget *alignment2;
  GtkWidget *vbox_tool_back;
  GtkWidget *image_back;
  GtkWidget *label_back;
  GtkWidget *toolitem_up;
  GtkWidget *button_up;
  GtkWidget *alignment3;
  GtkWidget *vbox_tool_up;
  GtkWidget *image_up;
  GtkWidget *label_up;
  GtkWidget *toolitem_tool;
  GtkWidget *vseparator_tool;
  GtkWidget *toolitem_downolad;
  GtkWidget *button_download;
  GtkWidget *alignment4;
  GtkWidget *vbox_tool_download;
  GtkWidget *image_download;
  GtkWidget *label_download;
  GtkWidget *toolitem_upload;
  GtkWidget *button_upload;
  GtkWidget *alignment5;
  GtkWidget *vbox8;
  GtkWidget *image_upload;
  GtkWidget *label_upload;
  GtkWidget *notebook_main;
  GtkWidget *hbox_notebook;
  GtkWidget *image_sinfo;
  GtkWidget *vbox_sinfo;
  GtkWidget *label_hostname;
  GtkWidget *hseparator_one;
  GtkWidget *label_release;
  GtkWidget *label_kernel;
  GtkWidget *label_memory;
  GtkWidget *hseparator_two;
  GtkWidget *label_net;
  GtkWidget *hbox_net;
  GtkWidget *label_netrecv;
  GtkWidget *label_netsend;
  GtkWidget *hseparator_three;
  GtkWidget *label_cpuinfo;
  GtkWidget *label_cpuused;
  GtkWidget *label_cpuload;
  GtkWidget *hseparator_four;
  GtkWidget *label_disk;
  GtkWidget *label_ssinfo;
  GtkWidget *scrolledwindow_process;
  GtkWidget *clist_process;
  GtkWidget *label_name;
  GtkWidget *label_pid;
  GtkWidget *label_status;
  GtkWidget *label_cpu;
  GtkWidget *label_mem;
  GtkWidget *label_sprocess;
  GtkWidget *vbox9;
  GtkWidget *vbox10;
  GtkWidget *hbox1;
  GtkWidget *label_fpath;
  GtkWidget *entry_fpath;
  GtkWidget *scrolledwindow_fview;
  GtkWidget *clist_fview;
  GtkWidget *label_fname;
  GtkWidget *label_fsize;
  GtkWidget *label_ftype;
  GtkWidget *label_fmdate;
  GtkWidget *label_fview;
  GtkWidget *frame_main;
  GtkWidget *alignment_frame;
  GtkWidget *vbox_frame;
  GtkWidget *scrolledwindow_frame;
  GtkWidget *textview_ctrl;
  GtkWidget *entry_input;
  GtkWidget *label_frame;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_main, 800, 650);
  GTK_WIDGET_SET_FLAGS (window_main, GTK_CAN_FOCUS);
  gtk_window_set_title (GTK_WINDOW (window_main), _("Linux ARMS(hostclient)"));
  gtk_window_set_position (GTK_WINDOW (window_main), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_main), 800, 650);

  vbox_main = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_main);
  gtk_container_add (GTK_CONTAINER (window_main), vbox_main);

  menubar = gtk_menu_bar_new ();
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox_main), menubar, FALSE, FALSE, 0);

  menubar_file = gtk_menu_item_new_with_mnemonic (_("\346\226\207\344\273\266(_F)"));
  gtk_widget_show (menubar_file);
  gtk_container_add (GTK_CONTAINER (menubar), menubar_file);

  menubar_file_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_file), menubar_file_menu);

  login = gtk_image_menu_item_new_with_mnemonic (_("\347\231\273\345\275\225arm\347\263\273\347\273\237"));
  gtk_widget_show (login);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), login);
  gtk_tooltips_set_tip (tooltips, login, _("\347\231\273\345\275\225arm\347\263\273\347\273\237"), NULL);

  image336 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image336);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (login), image336);

  logout = gtk_image_menu_item_new_with_mnemonic (_("\346\263\250\351\224\200\347\224\250\346\210\267\347\231\273\345\275\225"));
  gtk_widget_show (logout);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), logout);
  gtk_tooltips_set_tip (tooltips, logout, _("\346\263\250\351\224\200\345\275\223\345\211\215\347\224\250\346\210\267"), NULL);

  image337 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image337);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (logout), image337);

  file_separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (file_separator_one);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), file_separator_one);
  gtk_widget_set_sensitive (file_separator_one, FALSE);

  restart = gtk_image_menu_item_new_with_mnemonic (_("\351\207\215\345\220\257arm\347\263\273\347\273\237"));
  gtk_widget_show (restart);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), restart);

  image338 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image338);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (restart), image338);

  shutdown = gtk_image_menu_item_new_with_mnemonic (_("\345\205\263\346\257\225arm\347\263\273\347\273\237"));
  gtk_widget_show (shutdown);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), shutdown);
  gtk_tooltips_set_tip (tooltips, shutdown, _("\345\205\263\351\227\255arm\347\263\273\347\273\237"), NULL);

  image339 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image339);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (shutdown), image339);

  file_separator_two = gtk_separator_menu_item_new ();
  gtk_widget_show (file_separator_two);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), file_separator_two);
  gtk_widget_set_sensitive (file_separator_two, FALSE);

  quit = gtk_image_menu_item_new_with_mnemonic (_("\351\200\200\345\207\272"));
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), quit);
  gtk_widget_add_accelerator (quit, "activate", accel_group,
                              GDK_Q, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image340 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image340);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit), image340);

  menubar_process = gtk_menu_item_new_with_mnemonic (_("\350\277\233\347\250\213(_P)"));
  gtk_widget_show (menubar_process);
  gtk_container_add (GTK_CONTAINER (menubar), menubar_process);

  menubar_process_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_process), menubar_process_menu);

  process_update_three = gtk_radio_menu_item_new_with_mnemonic (process_update_three_group, _("\346\233\264\346\226\260(3\347\247\222)"));
  process_update_three_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (process_update_three));
  gtk_widget_show (process_update_three);
  gtk_container_add (GTK_CONTAINER (menubar_process_menu), process_update_three);
  gtk_tooltips_set_tip (tooltips, process_update_three, _("\346\257\217\351\232\2243\347\247\222\351\222\237\346\233\264\346\226\260\344\270\200\346\254\241"), NULL);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (process_update_three), TRUE);

  process_update_five = gtk_radio_menu_item_new_with_mnemonic (process_update_three_group, _("\346\233\264\346\226\260(5\347\247\222)"));
  process_update_three_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (process_update_five));
  gtk_widget_show (process_update_five);
  gtk_container_add (GTK_CONTAINER (menubar_process_menu), process_update_five);
  gtk_tooltips_set_tip (tooltips, process_update_five, _("\346\257\217\351\232\2245\347\247\222\351\222\237\346\233\264\346\226\260\344\270\200\346\254\241"), NULL);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (process_update_five), TRUE);

  separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (separator_one);
  gtk_container_add (GTK_CONTAINER (menubar_process_menu), separator_one);
  gtk_widget_set_sensitive (separator_one, FALSE);

  process_kill = gtk_image_menu_item_new_with_mnemonic (_("\346\235\200\346\255\273"));
  gtk_widget_show (process_kill);
  gtk_container_add (GTK_CONTAINER (menubar_process_menu), process_kill);
  gtk_tooltips_set_tip (tooltips, process_kill, _("\346\235\200\346\255\273\351\200\211\344\270\255\347\232\204\350\277\233\347\250\213"), NULL);
  gtk_widget_add_accelerator (process_kill, "activate", accel_group,
                              GDK_K, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image341 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image341);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (process_kill), image341);

  menubar_fview = gtk_menu_item_new_with_mnemonic (_("\346\265\217\350\247\210(_V)"));
  gtk_widget_show (menubar_fview);
  gtk_container_add (GTK_CONTAINER (menubar), menubar_fview);

  menubar_fview_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_fview), menubar_fview_menu);

  fview_rename = gtk_image_menu_item_new_with_mnemonic (_("\351\207\215\345\221\275\345\220\215\346\226\207\344\273\266"));
  gtk_widget_show (fview_rename);
  gtk_container_add (GTK_CONTAINER (menubar_fview_menu), fview_rename);
  gtk_tooltips_set_tip (tooltips, fview_rename, _("\351\207\215\345\221\275\345\220\215\351\200\211\344\270\255\347\232\204\346\226\207\344\273\266"), NULL);
  gtk_widget_add_accelerator (fview_rename, "activate", accel_group,
                              GDK_F2, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image342 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image342);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (fview_rename), image342);

  fview_delete = gtk_image_menu_item_new_with_mnemonic (_("\345\210\240\351\231\244\346\226\207\344\273\266"));
  gtk_widget_show (fview_delete);
  gtk_container_add (GTK_CONTAINER (menubar_fview_menu), fview_delete);
  gtk_tooltips_set_tip (tooltips, fview_delete, _("\345\210\240\351\231\244\351\200\211\344\270\255\347\232\204\346\226\207\344\273\266"), NULL);

  image343 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image343);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (fview_delete), image343);

  edit_separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (edit_separator_one);
  gtk_container_add (GTK_CONTAINER (menubar_fview_menu), edit_separator_one);
  gtk_widget_set_sensitive (edit_separator_one, FALSE);

  fview_upload = gtk_image_menu_item_new_with_mnemonic (_("\344\270\212\344\274\240\346\226\207\344\273\266"));
  gtk_widget_show (fview_upload);
  gtk_container_add (GTK_CONTAINER (menubar_fview_menu), fview_upload);
  gtk_tooltips_set_tip (tooltips, fview_upload, _("\344\273\216arm\347\263\273\347\273\237\344\270\212\344\274\240\346\226\207\344\273\266\345\210\260\346\234\254\346\234\272"), NULL);
  gtk_widget_add_accelerator (fview_upload, "activate", accel_group,
                              GDK_U, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image344 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image344);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (fview_upload), image344);

  fview_downolad = gtk_image_menu_item_new_with_mnemonic (_("\344\270\213\350\275\275\346\226\207\344\273\266"));
  gtk_widget_show (fview_downolad);
  gtk_container_add (GTK_CONTAINER (menubar_fview_menu), fview_downolad);
  gtk_tooltips_set_tip (tooltips, fview_downolad, _("\344\273\216\346\234\254\346\234\272\344\270\213\350\275\275\346\226\207\344\273\266\345\210\260arm\347\263\273\347\273\237\344\270\212"), NULL);
  gtk_widget_add_accelerator (fview_downolad, "activate", accel_group,
                              GDK_D, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image345 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image345);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (fview_downolad), image345);

  menubar_help = gtk_menu_item_new_with_mnemonic (_("\345\270\256\345\212\251(_H)"));
  gtk_widget_show (menubar_help);
  gtk_container_add (GTK_CONTAINER (menubar), menubar_help);

  menubar_help_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_help), menubar_help_menu);

  help_topic = gtk_image_menu_item_new_with_mnemonic (_("\345\270\256\345\212\251\344\270\273\351\242\230"));
  gtk_widget_show (help_topic);
  gtk_container_add (GTK_CONTAINER (menubar_help_menu), help_topic);
  gtk_tooltips_set_tip (tooltips, help_topic, _("\345\270\256\345\212\251\346\226\207\346\241\243"), NULL);
  gtk_widget_add_accelerator (help_topic, "activate", accel_group,
                              GDK_F1, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image346 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image346);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (help_topic), image346);

  help_separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (help_separator_one);
  gtk_container_add (GTK_CONTAINER (menubar_help_menu), help_separator_one);
  gtk_widget_set_sensitive (help_separator_one, FALSE);

  help_about = gtk_image_menu_item_new_with_mnemonic (_("\345\205\263\344\272\216"));
  gtk_widget_show (help_about);
  gtk_container_add (GTK_CONTAINER (menubar_help_menu), help_about);
  gtk_tooltips_set_tip (tooltips, help_about, _("\345\205\263\344\272\216\346\234\254\350\275\257\344\273\266"), NULL);
  gtk_widget_add_accelerator (help_about, "activate", accel_group,
                              GDK_A, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image347 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image347);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (help_about), image347);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gtk_box_pack_start (GTK_BOX (vbox_main), toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar));

  toolitem_back = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_back);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_back);

  button_back = gtk_button_new ();
  gtk_widget_show (button_back);
  gtk_container_add (GTK_CONTAINER (toolitem_back), button_back);
  gtk_widget_set_size_request (button_back, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_back, _("\350\277\224\345\233\236\345\210\260\345\210\232\346\211\215\350\256\277\351\227\256\350\277\207\347\232\204\347\233\256\345\275\225"), NULL);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_back), alignment2);

  vbox_tool_back = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_tool_back);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox_tool_back);

  image_back = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_back);
  gtk_box_pack_start (GTK_BOX (vbox_tool_back), image_back, TRUE, TRUE, 0);

  label_back = gtk_label_new (_("\345\220\216\351\200\200"));
  gtk_widget_show (label_back);
  gtk_box_pack_start (GTK_BOX (vbox_tool_back), label_back, FALSE, FALSE, 0);

  toolitem_up = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_up);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_up);

  button_up = gtk_button_new ();
  gtk_widget_show (button_up);
  gtk_container_add (GTK_CONTAINER (toolitem_up), button_up);
  gtk_widget_set_size_request (button_up, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_up, _("\350\277\224\345\233\236\344\270\212\347\272\247\347\233\256\345\275\225"), NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_up), alignment3);

  vbox_tool_up = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_tool_up);
  gtk_container_add (GTK_CONTAINER (alignment3), vbox_tool_up);

  image_up = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_up);
  gtk_box_pack_start (GTK_BOX (vbox_tool_up), image_up, TRUE, TRUE, 0);

  label_up = gtk_label_new (_("\345\220\221\344\270\212"));
  gtk_widget_show (label_up);
  gtk_box_pack_start (GTK_BOX (vbox_tool_up), label_up, FALSE, FALSE, 0);

  toolitem_tool = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_tool);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_tool);

  vseparator_tool = gtk_vseparator_new ();
  gtk_widget_show (vseparator_tool);
  gtk_container_add (GTK_CONTAINER (toolitem_tool), vseparator_tool);
  gtk_widget_set_size_request (vseparator_tool, 5, -1);

  toolitem_downolad = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_downolad);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_downolad);

  button_download = gtk_button_new ();
  gtk_widget_show (button_download);
  gtk_container_add (GTK_CONTAINER (toolitem_downolad), button_download);
  gtk_widget_set_size_request (button_download, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_download, _("\344\273\216\346\234\254\346\234\272\344\270\213\350\275\275\346\226\207\344\273\266\345\210\260arm\347\263\273\347\273\237\344\270\212"), NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_download), alignment4);

  vbox_tool_download = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_tool_download);
  gtk_container_add (GTK_CONTAINER (alignment4), vbox_tool_download);

  image_download = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_download);
  gtk_box_pack_start (GTK_BOX (vbox_tool_download), image_download, TRUE, TRUE, 0);

  label_download = gtk_label_new (_("\344\270\213\350\275\275"));
  gtk_widget_show (label_download);
  gtk_box_pack_start (GTK_BOX (vbox_tool_download), label_download, FALSE, FALSE, 0);

  toolitem_upload = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_upload);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_upload);

  button_upload = gtk_button_new ();
  gtk_widget_show (button_upload);
  gtk_container_add (GTK_CONTAINER (toolitem_upload), button_upload);
  gtk_widget_set_size_request (button_upload, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_upload, _("\344\273\216arm\347\263\273\347\273\237\344\270\212\344\274\240\346\226\207\344\273\266\345\210\260\346\234\254\346\234\272\344\270\212"), NULL);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_upload), alignment5);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (alignment5), vbox8);

  image_upload = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_upload);
  gtk_box_pack_start (GTK_BOX (vbox8), image_upload, TRUE, TRUE, 0);

  label_upload = gtk_label_new (_("\344\270\212\344\274\240"));
  gtk_widget_show (label_upload);
  gtk_box_pack_start (GTK_BOX (vbox8), label_upload, FALSE, FALSE, 0);

  notebook_main = gtk_notebook_new ();
  gtk_widget_show (notebook_main);
  gtk_box_pack_start (GTK_BOX (vbox_main), notebook_main, TRUE, TRUE, 0);

  hbox_notebook = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_notebook);
  gtk_container_add (GTK_CONTAINER (notebook_main), hbox_notebook);
  GTK_WIDGET_SET_FLAGS (hbox_notebook, GTK_CAN_FOCUS);

  image_sinfo = create_pixmap (window_main, "linuxarms.png");
  gtk_widget_show (image_sinfo);
  gtk_box_pack_start (GTK_BOX (hbox_notebook), image_sinfo, TRUE, TRUE, 0);
  gtk_widget_set_size_request (image_sinfo, 247, 230);

  vbox_sinfo = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_sinfo);
  gtk_box_pack_start (GTK_BOX (hbox_notebook), vbox_sinfo, TRUE, TRUE, 0);

  label_hostname = gtk_label_new (_("<b>\344\270\273\346\234\272\345\220\215\357\274\232</b>"));
  gtk_widget_show (label_hostname);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_hostname, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_hostname, -1, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_hostname), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_hostname), 0, 0.5);

  hseparator_one = gtk_hseparator_new ();
  gtk_widget_show (hseparator_one);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), hseparator_one, FALSE, TRUE, 0);

  label_release = gtk_label_new (_("<b>    \345\217\221\350\241\214\347\211\210\346\234\254  </b>"));
  gtk_widget_show (label_release);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_release, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_release, -1, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_release), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_release), 0, 0.5);

  label_kernel = gtk_label_new (_("<b>    \345\206\205\346\240\270\347\211\210\346\234\254 </b>"));
  gtk_widget_show (label_kernel);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_kernel, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_kernel, -1, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_kernel), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_kernel), 0, 0.5);

  label_memory = gtk_label_new (_(" \345\206\205\345\255\230\357\274\232\346\200\273\351\207\217(M) | \344\275\277\347\224\250(M)"));
  gtk_widget_show (label_memory);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_memory, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_memory, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label_memory), 0, 0.5);

  hseparator_two = gtk_hseparator_new ();
  gtk_widget_show (hseparator_two);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), hseparator_two, FALSE, TRUE, 0);

  label_net = gtk_label_new (_("<b>\347\275\221\347\273\234\344\275\277\347\224\250</b>"));
  gtk_widget_show (label_net);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_net, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_net, -1, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_net), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_net), 0, 0.5);

  hbox_net = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_net);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), hbox_net, FALSE, TRUE, 0);

  label_netrecv = gtk_label_new (_("\346\216\245\346\224\266: kb"));
  gtk_widget_show (label_netrecv);
  gtk_box_pack_start (GTK_BOX (hbox_net), label_netrecv, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_netrecv, 164, -1);
  gtk_misc_set_alignment (GTK_MISC (label_netrecv), 0.15, 0.5);

  label_netsend = gtk_label_new (_("\345\217\221\351\200\201: kb"));
  gtk_widget_show (label_netsend);
  gtk_box_pack_start (GTK_BOX (hbox_net), label_netsend, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_netsend, 163, 25);
  gtk_misc_set_alignment (GTK_MISC (label_netsend), 0, 0.5);

  hseparator_three = gtk_hseparator_new ();
  gtk_widget_show (hseparator_three);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), hseparator_three, FALSE, TRUE, 0);

  label_cpuinfo = gtk_label_new (_("<b>CPU\345\236\213\345\217\267 </b>"));
  gtk_widget_show (label_cpuinfo);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_cpuinfo, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_cpuinfo, -1, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_cpuinfo), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_cpuinfo), 0, 0.5);

  label_cpuused = gtk_label_new (_("\344\275\277\347\224\250\347\216\207\357\274\232"));
  gtk_widget_show (label_cpuused);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_cpuused, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_cpuused, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label_cpuused), 0.03, 0.5);

  label_cpuload = gtk_label_new (_("CPU\350\264\237\350\275\275\357\274\232"));
  gtk_widget_show (label_cpuload);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_cpuload, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_cpuload, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label_cpuload), 0.03, 0.5);

  hseparator_four = gtk_hseparator_new ();
  gtk_widget_show (hseparator_four);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), hseparator_four, FALSE, TRUE, 0);

  label_disk = gtk_label_new (_("\347\241\254\347\233\230\357\274\232\346\200\273\345\256\271\351\207\217(M) | \344\275\277\347\224\250(M)"));
  gtk_widget_show (label_disk);
  gtk_box_pack_start (GTK_BOX (vbox_sinfo), label_disk, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_disk, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label_disk), 0, 0.5);

  label_ssinfo = gtk_label_new (_("\347\263\273\347\273\237\344\277\241\346\201\257"));
  gtk_widget_show (label_ssinfo);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_main), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_main), 0), label_ssinfo);
  GTK_WIDGET_SET_FLAGS (label_ssinfo, GTK_CAN_FOCUS);

  scrolledwindow_process = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_process);
  gtk_container_add (GTK_CONTAINER (notebook_main), scrolledwindow_process);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_process), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow_process), GTK_SHADOW_IN);

  clist_process = gtk_clist_new (5);
  gtk_widget_show (clist_process);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_process), clist_process);
  gtk_clist_set_column_width (GTK_CLIST (clist_process), 0, 196);
  gtk_clist_set_column_width (GTK_CLIST (clist_process), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_process), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_process), 3, 98);
  gtk_clist_set_column_width (GTK_CLIST (clist_process), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist_process));

  label_name = gtk_label_new (_("\350\277\233\347\250\213\345\220\215"));
  gtk_widget_show (label_name);
  gtk_clist_set_column_widget (GTK_CLIST (clist_process), 0, label_name);

  label_pid = gtk_label_new (_("\350\277\233\347\250\213\345\217\267"));
  gtk_widget_show (label_pid);
  gtk_clist_set_column_widget (GTK_CLIST (clist_process), 1, label_pid);

  label_status = gtk_label_new (_("\350\277\233\347\250\213\347\212\266\346\200\201"));
  gtk_widget_show (label_status);
  gtk_clist_set_column_widget (GTK_CLIST (clist_process), 2, label_status);

  label_cpu = gtk_label_new (_("CPU\344\275\277\347\224\250\347\216\207"));
  gtk_widget_show (label_cpu);
  gtk_clist_set_column_widget (GTK_CLIST (clist_process), 3, label_cpu);

  label_mem = gtk_label_new (_("\345\206\205\345\255\230\344\275\277\347\224\250\351\207\217"));
  gtk_widget_show (label_mem);
  gtk_clist_set_column_widget (GTK_CLIST (clist_process), 4, label_mem);

  label_sprocess = gtk_label_new (_("\347\263\273\347\273\237\350\277\233\347\250\213"));
  gtk_widget_show (label_sprocess);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_main), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_main), 1), label_sprocess);
  GTK_WIDGET_SET_FLAGS (label_sprocess, GTK_CAN_FOCUS);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (notebook_main), vbox9);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (vbox9), vbox10, FALSE, FALSE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox1, TRUE, TRUE, 0);

  label_fpath = gtk_label_new (_("\346\226\207\344\273\266\350\267\257\345\276\204"));
  gtk_widget_show (label_fpath);
  gtk_box_pack_start (GTK_BOX (hbox1), label_fpath, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label_fpath, 60, -1);

  entry_fpath = gtk_entry_new ();
  gtk_widget_show (entry_fpath);
  gtk_box_pack_start (GTK_BOX (hbox1), entry_fpath, TRUE, TRUE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (entry_fpath), 256);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_fpath), 9679);

  scrolledwindow_fview = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_fview);
  gtk_box_pack_start (GTK_BOX (vbox9), scrolledwindow_fview, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_fview), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow_fview), GTK_SHADOW_IN);

  clist_fview = gtk_clist_new (4);
  gtk_widget_show (clist_fview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_fview), clist_fview);
  gtk_clist_set_column_width (GTK_CLIST (clist_fview), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_fview), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_fview), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_fview), 3, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist_fview));

  label_fname = gtk_label_new (_("\346\226\207\344\273\266\345\220\215"));
  gtk_widget_show (label_fname);
  gtk_clist_set_column_widget (GTK_CLIST (clist_fview), 0, label_fname);

  label_fsize = gtk_label_new (_("\345\244\247\345\260\217"));
  gtk_widget_show (label_fsize);
  gtk_clist_set_column_widget (GTK_CLIST (clist_fview), 1, label_fsize);

  label_ftype = gtk_label_new (_("\347\261\273\345\236\213"));
  gtk_widget_show (label_ftype);
  gtk_clist_set_column_widget (GTK_CLIST (clist_fview), 2, label_ftype);

  label_fmdate = gtk_label_new (_("\344\277\256\346\224\271\346\227\266\351\227\264"));
  gtk_widget_show (label_fmdate);
  gtk_clist_set_column_widget (GTK_CLIST (clist_fview), 3, label_fmdate);

  label_fview = gtk_label_new (_("\346\265\217\350\247\210\346\226\207\344\273\266"));
  gtk_widget_show (label_fview);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_main), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_main), 2), label_fview);
  GTK_WIDGET_SET_FLAGS (label_fview, GTK_CAN_FOCUS);

  frame_main = gtk_frame_new (NULL);
  gtk_widget_show (frame_main);
  gtk_box_pack_start (GTK_BOX (vbox_main), frame_main, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_main), GTK_SHADOW_NONE);

  alignment_frame = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment_frame);
  gtk_container_add (GTK_CONTAINER (frame_main), alignment_frame);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment_frame), 0, 0, 12, 0);

  vbox_frame = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_frame);
  gtk_container_add (GTK_CONTAINER (alignment_frame), vbox_frame);

  scrolledwindow_frame = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_frame);
  gtk_box_pack_start (GTK_BOX (vbox_frame), scrolledwindow_frame, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_frame), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow_frame), GTK_SHADOW_IN);

  textview_ctrl = gtk_text_view_new ();
  gtk_widget_show (textview_ctrl);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_frame), textview_ctrl);
  GTK_WIDGET_UNSET_FLAGS (textview_ctrl, GTK_CAN_FOCUS);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview_ctrl), FALSE);

  entry_input = gtk_entry_new ();
  gtk_widget_show (entry_input);
  gtk_box_pack_start (GTK_BOX (vbox_frame), entry_input, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, entry_input, _("\350\276\223\345\205\245\345\221\275\344\273\244"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_input), 256);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_input), 9679);
  gtk_entry_set_text(GTK_ENTRY(entry_input),"root&");

  label_frame = gtk_label_new (_("<b>\345\256\236\346\227\266\346\216\247\345\210\266</b>"));
  gtk_widget_show (label_frame);
  gtk_frame_set_label_widget (GTK_FRAME (frame_main), label_frame);
  gtk_label_set_use_markup (GTK_LABEL (label_frame), TRUE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox_main), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window_main, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) login, "activate",
                    G_CALLBACK (cb_login_activate),
                    NULL);
  g_signal_connect ((gpointer) logout, "activate",
                    G_CALLBACK (cb_logout_activate),
                    NULL);
  g_signal_connect ((gpointer) restart, "activate",
                    G_CALLBACK (cb_restart_activate),
                    NULL);
  g_signal_connect ((gpointer) shutdown, "activate",
                    G_CALLBACK (cb_shutdown_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) process_update_three, "activate",
                    G_CALLBACK (cb_process_update_three_activate),
                    NULL);
  g_signal_connect ((gpointer) process_update_five, "activate",
                    G_CALLBACK (cb_process_update_five_activate),
                    NULL);
  g_signal_connect ((gpointer) process_kill, "activate",
                    G_CALLBACK (cb_process_kill_activate),
                    NULL);
  g_signal_connect ((gpointer) fview_rename, "activate",
                    G_CALLBACK (cb_fview_rename_activate),
                    NULL);
  g_signal_connect ((gpointer) fview_delete, "activate",
                    G_CALLBACK (cb_fview_delete_activate),
                    NULL);
  g_signal_connect ((gpointer) fview_upload, "activate",
                    G_CALLBACK (cb_fview_upload_activate),
                    NULL);
  g_signal_connect ((gpointer) fview_downolad, "activate",
                    G_CALLBACK (cb_fview_downolad_activate),
                    NULL);
  g_signal_connect ((gpointer) help_topic, "activate",
                    G_CALLBACK (cb_help_topic_activate),
                    NULL);
  g_signal_connect ((gpointer) help_about, "activate",
                    G_CALLBACK (cb_help_about_activate),
                    NULL);
  g_signal_connect ((gpointer) button_back, "clicked",
                    G_CALLBACK (cb_fview_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_up, "clicked",
                    G_CALLBACK (cb_fview_up_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_download, "clicked",
                    G_CALLBACK (cb_download_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_upload, "clicked",
                    G_CALLBACK (cb_upload_clicked),
                    NULL);
  g_signal_connect ((gpointer) notebook_main, "switch_page",
                    G_CALLBACK (cb_notebook_switch_page),
                    NULL);
  g_signal_connect ((gpointer) clist_process, "click_column",
                    G_CALLBACK (cb_clist_process_click_column),
                    NULL);
  g_signal_connect ((gpointer) clist_process, "button_press_event",
                    G_CALLBACK (cb_clist_process_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) clist_fview, "click_column",
                    G_CALLBACK (cb_clist_fview_click_column),
                    NULL);
  g_signal_connect ((gpointer) clist_fview, "button_press_event",
                    G_CALLBACK (cb_clist_fview_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) entry_input, "key_press_event",
                    G_CALLBACK (cb_ctrl_input_key_press),
                    NULL);
  g_signal_connect ((gpointer) entry_input, "delete_text",
                    G_CALLBACK (cb_entry_input_delete_text),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_main, window_main, "window_main");
  GLADE_HOOKUP_OBJECT (window_main, vbox_main, "vbox_main");
  GLADE_HOOKUP_OBJECT (window_main, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (window_main, menubar_file, "menubar_file");
  GLADE_HOOKUP_OBJECT (window_main, menubar_file_menu, "menubar_file_menu");
  GLADE_HOOKUP_OBJECT (window_main, login, "login");
  GLADE_HOOKUP_OBJECT (window_main, image336, "image336");
  GLADE_HOOKUP_OBJECT (window_main, logout, "logout");
  GLADE_HOOKUP_OBJECT (window_main, image337, "image337");
  GLADE_HOOKUP_OBJECT (window_main, file_separator_one, "file_separator_one");
  GLADE_HOOKUP_OBJECT (window_main, restart, "restart");
  GLADE_HOOKUP_OBJECT (window_main, image338, "image338");
  GLADE_HOOKUP_OBJECT (window_main, shutdown, "shutdown");
  GLADE_HOOKUP_OBJECT (window_main, image339, "image339");
  GLADE_HOOKUP_OBJECT (window_main, file_separator_two, "file_separator_two");
  GLADE_HOOKUP_OBJECT (window_main, quit, "quit");
  GLADE_HOOKUP_OBJECT (window_main, image340, "image340");
  GLADE_HOOKUP_OBJECT (window_main, menubar_process, "menubar_process");
  GLADE_HOOKUP_OBJECT (window_main, menubar_process_menu, "menubar_process_menu");
  GLADE_HOOKUP_OBJECT (window_main, process_update_three, "process_update_three");
  GLADE_HOOKUP_OBJECT (window_main, process_update_five, "process_update_five");
  GLADE_HOOKUP_OBJECT (window_main, separator_one, "separator_one");
  GLADE_HOOKUP_OBJECT (window_main, process_kill, "process_kill");
  GLADE_HOOKUP_OBJECT (window_main, image341, "image341");
  GLADE_HOOKUP_OBJECT (window_main, menubar_fview, "menubar_fview");
  GLADE_HOOKUP_OBJECT (window_main, menubar_fview_menu, "menubar_fview_menu");
  GLADE_HOOKUP_OBJECT (window_main, fview_rename, "fview_rename");
  GLADE_HOOKUP_OBJECT (window_main, image342, "image342");
  GLADE_HOOKUP_OBJECT (window_main, fview_delete, "fview_delete");
  GLADE_HOOKUP_OBJECT (window_main, image343, "image343");
  GLADE_HOOKUP_OBJECT (window_main, edit_separator_one, "edit_separator_one");
  GLADE_HOOKUP_OBJECT (window_main, fview_upload, "fview_upload");
  GLADE_HOOKUP_OBJECT (window_main, image344, "image344");
  GLADE_HOOKUP_OBJECT (window_main, fview_downolad, "fview_downolad");
  GLADE_HOOKUP_OBJECT (window_main, image345, "image345");
  GLADE_HOOKUP_OBJECT (window_main, menubar_help, "menubar_help");
  GLADE_HOOKUP_OBJECT (window_main, menubar_help_menu, "menubar_help_menu");
  GLADE_HOOKUP_OBJECT (window_main, help_topic, "help_topic");
  GLADE_HOOKUP_OBJECT (window_main, image346, "image346");
  GLADE_HOOKUP_OBJECT (window_main, help_separator_one, "help_separator_one");
  GLADE_HOOKUP_OBJECT (window_main, help_about, "help_about");
  GLADE_HOOKUP_OBJECT (window_main, image347, "image347");
  GLADE_HOOKUP_OBJECT (window_main, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_back, "toolitem_back");
  GLADE_HOOKUP_OBJECT (window_main, button_back, "button_back");
  GLADE_HOOKUP_OBJECT (window_main, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_main, vbox_tool_back, "vbox_tool_back");
  GLADE_HOOKUP_OBJECT (window_main, image_back, "image_back");
  GLADE_HOOKUP_OBJECT (window_main, label_back, "label_back");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_up, "toolitem_up");
  GLADE_HOOKUP_OBJECT (window_main, button_up, "button_up");
  GLADE_HOOKUP_OBJECT (window_main, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_main, vbox_tool_up, "vbox_tool_up");
  GLADE_HOOKUP_OBJECT (window_main, image_up, "image_up");
  GLADE_HOOKUP_OBJECT (window_main, label_up, "label_up");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_tool, "toolitem_tool");
  GLADE_HOOKUP_OBJECT (window_main, vseparator_tool, "vseparator_tool");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_downolad, "toolitem_downolad");
  GLADE_HOOKUP_OBJECT (window_main, button_download, "button_download");
  GLADE_HOOKUP_OBJECT (window_main, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_main, vbox_tool_download, "vbox_tool_download");
  GLADE_HOOKUP_OBJECT (window_main, image_download, "image_download");
  GLADE_HOOKUP_OBJECT (window_main, label_download, "label_download");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_upload, "toolitem_upload");
  GLADE_HOOKUP_OBJECT (window_main, button_upload, "button_upload");
  GLADE_HOOKUP_OBJECT (window_main, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_main, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (window_main, image_upload, "image_upload");
  GLADE_HOOKUP_OBJECT (window_main, label_upload, "label_upload");
  GLADE_HOOKUP_OBJECT (window_main, notebook_main, "notebook_main");
  GLADE_HOOKUP_OBJECT (window_main, hbox_notebook, "hbox_notebook");
  GLADE_HOOKUP_OBJECT (window_main, image_sinfo, "image_sinfo");
  GLADE_HOOKUP_OBJECT (window_main, vbox_sinfo, "vbox_sinfo");
  GLADE_HOOKUP_OBJECT (window_main, label_hostname, "label_hostname");
  GLADE_HOOKUP_OBJECT (window_main, hseparator_one, "hseparator_one");
  GLADE_HOOKUP_OBJECT (window_main, label_release, "label_release");
  GLADE_HOOKUP_OBJECT (window_main, label_kernel, "label_kernel");
  GLADE_HOOKUP_OBJECT (window_main, label_memory, "label_memory");
  GLADE_HOOKUP_OBJECT (window_main, hseparator_two, "hseparator_two");
  GLADE_HOOKUP_OBJECT (window_main, label_net, "label_net");
  GLADE_HOOKUP_OBJECT (window_main, hbox_net, "hbox_net");
  GLADE_HOOKUP_OBJECT (window_main, label_netrecv, "label_netrecv");
  GLADE_HOOKUP_OBJECT (window_main, label_netsend, "label_netsend");
  GLADE_HOOKUP_OBJECT (window_main, hseparator_three, "hseparator_three");
  GLADE_HOOKUP_OBJECT (window_main, label_cpuinfo, "label_cpuinfo");
  GLADE_HOOKUP_OBJECT (window_main, label_cpuused, "label_cpuused");
  GLADE_HOOKUP_OBJECT (window_main, label_cpuload, "label_cpuload");
  GLADE_HOOKUP_OBJECT (window_main, hseparator_four, "hseparator_four");
  GLADE_HOOKUP_OBJECT (window_main, label_disk, "label_disk");
  GLADE_HOOKUP_OBJECT (window_main, label_ssinfo, "label_ssinfo");
  GLADE_HOOKUP_OBJECT (window_main, scrolledwindow_process, "scrolledwindow_process");
  GLADE_HOOKUP_OBJECT (window_main, clist_process, "clist_process");
  GLADE_HOOKUP_OBJECT (window_main, label_name, "label_name");
  GLADE_HOOKUP_OBJECT (window_main, label_pid, "label_pid");
  GLADE_HOOKUP_OBJECT (window_main, label_status, "label_status");
  GLADE_HOOKUP_OBJECT (window_main, label_cpu, "label_cpu");
  GLADE_HOOKUP_OBJECT (window_main, label_mem, "label_mem");
  GLADE_HOOKUP_OBJECT (window_main, label_sprocess, "label_sprocess");
  GLADE_HOOKUP_OBJECT (window_main, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (window_main, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (window_main, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_main, label_fpath, "label_fpath");
  GLADE_HOOKUP_OBJECT (window_main, entry_fpath, "entry_fpath");
  GLADE_HOOKUP_OBJECT (window_main, scrolledwindow_fview, "scrolledwindow_fview");
  GLADE_HOOKUP_OBJECT (window_main, clist_fview, "clist_fview");
  GLADE_HOOKUP_OBJECT (window_main, label_fname, "label_fname");
  GLADE_HOOKUP_OBJECT (window_main, label_fsize, "label_fsize");
  GLADE_HOOKUP_OBJECT (window_main, label_ftype, "label_ftype");
  GLADE_HOOKUP_OBJECT (window_main, label_fmdate, "label_fmdate");
  GLADE_HOOKUP_OBJECT (window_main, label_fview, "label_fview");
  GLADE_HOOKUP_OBJECT (window_main, frame_main, "frame_main");
  GLADE_HOOKUP_OBJECT (window_main, alignment_frame, "alignment_frame");
  GLADE_HOOKUP_OBJECT (window_main, vbox_frame, "vbox_frame");
  GLADE_HOOKUP_OBJECT (window_main, scrolledwindow_frame, "scrolledwindow_frame");
  GLADE_HOOKUP_OBJECT (window_main, textview_ctrl, "textview_ctrl");
  GLADE_HOOKUP_OBJECT (window_main, entry_input, "entry_input");
  GLADE_HOOKUP_OBJECT (window_main, label_frame, "label_frame");
  GLADE_HOOKUP_OBJECT (window_main, statusbar, "statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (window_main, tooltips, "tooltips");

  gtk_widget_grab_focus (notebook_main);
  gtk_window_add_accel_group (GTK_WINDOW (window_main), accel_group);

  return window_main;
}

GtkWidget*
create_popup_menu_process (void)
{
  GtkWidget *popup_menu_process;
  GtkWidget *spopup_eparator;
  GtkWidget *popup_process_kill;
  GtkWidget *image209;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  popup_menu_process = gtk_menu_new ();

  spopup_eparator = gtk_separator_menu_item_new ();
  gtk_widget_show (spopup_eparator);
  gtk_container_add (GTK_CONTAINER (popup_menu_process), spopup_eparator);
  gtk_widget_set_sensitive (spopup_eparator, FALSE);

  popup_process_kill = gtk_image_menu_item_new_with_mnemonic (_("\346\235\200\346\255\273\350\277\233\347\250\213"));
  gtk_widget_show (popup_process_kill);
  gtk_container_add (GTK_CONTAINER (popup_menu_process), popup_process_kill);
  gtk_tooltips_set_tip (tooltips, popup_process_kill, _("\346\235\200\346\255\273\350\257\245\350\277\233\347\250\213"), NULL);
  gtk_widget_add_accelerator (popup_process_kill, "activate", accel_group,
                              GDK_K, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image209 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image209);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (popup_process_kill), image209);

  g_signal_connect ((gpointer) popup_process_kill, "activate",
                    G_CALLBACK (cb_popup_process_kill_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (popup_menu_process, popup_menu_process, "popup_menu_process");
  GLADE_HOOKUP_OBJECT (popup_menu_process, spopup_eparator, "spopup_eparator");
  GLADE_HOOKUP_OBJECT (popup_menu_process, popup_process_kill, "popup_process_kill");
  GLADE_HOOKUP_OBJECT (popup_menu_process, image209, "image209");
  GLADE_HOOKUP_OBJECT_NO_REF (popup_menu_process, tooltips, "tooltips");

  gtk_menu_set_accel_group (GTK_MENU (popup_menu_process), accel_group);

  return popup_menu_process;
}

GtkWidget*
create_popup_menu_fview (void)
{
  GtkWidget *popup_menu_fview;
  GtkWidget *popup_separator;
  GtkWidget *fview_rename;
  GtkWidget *image203;
  GtkWidget *fview_delete;
  GtkWidget *image204;
  GtkWidget *edit_separator_one;
  GtkWidget *edit_upload;
  GtkWidget *image205;
  GtkWidget *edit_downolad;
  GtkWidget *image206;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  popup_menu_fview = gtk_menu_new ();

  popup_separator = gtk_separator_menu_item_new ();
  gtk_widget_show (popup_separator);
  gtk_container_add (GTK_CONTAINER (popup_menu_fview), popup_separator);
  gtk_widget_set_sensitive (popup_separator, FALSE);

  fview_rename = gtk_image_menu_item_new_with_mnemonic (_("\351\207\215\345\221\275\345\220\215\346\226\207\344\273\266"));
  gtk_widget_show (fview_rename);
  gtk_container_add (GTK_CONTAINER (popup_menu_fview), fview_rename);
  gtk_tooltips_set_tip (tooltips, fview_rename, _("\351\207\215\345\221\275\345\220\215\351\200\211\344\270\255\347\232\204\346\226\207\344\273\266"), NULL);
  gtk_widget_add_accelerator (fview_rename, "activate", accel_group,
                              GDK_F2, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image203 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image203);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (fview_rename), image203);

  fview_delete = gtk_image_menu_item_new_with_mnemonic (_("\345\210\240\351\231\244\346\226\207\344\273\266"));
  gtk_widget_show (fview_delete);
  gtk_container_add (GTK_CONTAINER (popup_menu_fview), fview_delete);
  gtk_tooltips_set_tip (tooltips, fview_delete, _("\345\210\240\351\231\244\351\200\211\344\270\255\347\232\204\346\226\207\344\273\266"), NULL);

  image204 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image204);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (fview_delete), image204);

  edit_separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (edit_separator_one);
  gtk_container_add (GTK_CONTAINER (popup_menu_fview), edit_separator_one);
  gtk_widget_set_sensitive (edit_separator_one, FALSE);

  edit_upload = gtk_image_menu_item_new_with_mnemonic (_("\344\270\212\344\274\240\346\226\207\344\273\266"));
  gtk_widget_show (edit_upload);
  gtk_container_add (GTK_CONTAINER (popup_menu_fview), edit_upload);
  gtk_tooltips_set_tip (tooltips, edit_upload, _("\344\273\216arm\347\263\273\347\273\237\344\270\212\344\274\240\346\226\207\344\273\266\345\210\260\346\234\254\346\234\272"), NULL);
  gtk_widget_add_accelerator (edit_upload, "activate", accel_group,
                              GDK_U, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image205 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image205);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (edit_upload), image205);

  edit_downolad = gtk_image_menu_item_new_with_mnemonic (_("\344\270\213\350\275\275\346\226\207\344\273\266"));
  gtk_widget_show (edit_downolad);
  gtk_container_add (GTK_CONTAINER (popup_menu_fview), edit_downolad);
  gtk_tooltips_set_tip (tooltips, edit_downolad, _("\344\273\216\346\234\254\346\234\272\344\270\213\350\275\275\346\226\207\344\273\266\345\210\260arm\347\263\273\347\273\237\344\270\212"), NULL);
  gtk_widget_add_accelerator (edit_downolad, "activate", accel_group,
                              GDK_D, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image206 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image206);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (edit_downolad), image206);

  g_signal_connect ((gpointer) fview_rename, "activate",
                    G_CALLBACK (cb_fview_rename_activate),
                    NULL);
  g_signal_connect ((gpointer) fview_delete, "activate",
                    G_CALLBACK (cb_fview_delete_activate),
                    NULL);
  g_signal_connect ((gpointer) edit_upload, "activate",
                    G_CALLBACK (cb_fview_upload_activate),
                    NULL);
  g_signal_connect ((gpointer) edit_downolad, "activate",
                    G_CALLBACK (cb_fview_downolad_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (popup_menu_fview, popup_menu_fview, "popup_menu_fview");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, popup_separator, "popup_separator");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, fview_rename, "fview_rename");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, image203, "image203");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, fview_delete, "fview_delete");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, image204, "image204");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, edit_separator_one, "edit_separator_one");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, edit_upload, "edit_upload");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, image205, "image205");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, edit_downolad, "edit_downolad");
  GLADE_HOOKUP_OBJECT (popup_menu_fview, image206, "image206");
  GLADE_HOOKUP_OBJECT_NO_REF (popup_menu_fview, tooltips, "tooltips");

  gtk_menu_set_accel_group (GTK_MENU (popup_menu_fview), accel_group);

  return popup_menu_fview;
}

GtkWidget*
create_window_login (void)
{
  GtkWidget *window_login;
  GtkWidget *vbox_login;
  GtkWidget *image_login;
  GtkWidget *table_login;
  GtkWidget *label_ip;
  GtkWidget *label_name;
  GtkWidget *label_passwd;
  GtkWidget *comboboxentry_name;
  GtkWidget *comboboxentry_ip;
  GtkWidget *hbox5;
  GtkWidget *entry_passwd;
  GtkWidget *fixed5;
  GtkWidget *checkbutton_rem;
  GtkWidget *hbox2;
  GtkWidget *button_help;
  GtkWidget *alignment8;
  GtkWidget *hbox6;
  GtkWidget *image324;
  GtkWidget *label6;
  GtkWidget *fixed4;
  GtkWidget *button_cancel;
  GtkWidget *alignment6;
  GtkWidget *hbox3;
  GtkWidget *image322;
  GtkWidget *label_cancel;
  GtkWidget *button_ok;
  GtkWidget *alignment7;
  GtkWidget *hbox4;
  GtkWidget *image323;
  GtkWidget *label5;

  window_login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_login, 291, 290);
  gtk_window_set_title (GTK_WINDOW (window_login), _("Linuxarms\357\274\210arm\345\256\236\346\227\266\347\233\221\346\216\247\347\263\273\347\273\237\347\231\273\345\275\225\357\274\211"));
  gtk_window_set_position (GTK_WINDOW (window_login), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_login), 330, 262);
  gtk_window_set_resizable (GTK_WINDOW (window_login), FALSE);

  vbox_login = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_login);
  gtk_container_add (GTK_CONTAINER (window_login), vbox_login);
  gtk_container_set_border_width (GTK_CONTAINER (vbox_login), 4);

  image_login = create_pixmap (window_login, "login.png");
  gtk_widget_show (image_login);
  gtk_box_pack_start (GTK_BOX (vbox_login), image_login, FALSE, TRUE, 0);
  gtk_widget_set_size_request (image_login, 313, 130);

  table_login = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table_login);
  gtk_box_pack_start (GTK_BOX (vbox_login), table_login, FALSE, FALSE, 0);
  gtk_widget_set_size_request (table_login, -1, 89);

  label_ip = gtk_label_new (_("arm\347\263\273\347\273\237IP:"));
  gtk_widget_show (label_ip);
  gtk_table_attach (GTK_TABLE (table_login), label_ip, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_ip), 0, 0.5);

  label_name = gtk_label_new (_("\347\231\273\345\275\225\347\224\250\346\210\267\345\220\215:"));
  gtk_widget_show (label_name);
  gtk_table_attach (GTK_TABLE (table_login), label_name, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_name), 0, 0.5);

  label_passwd = gtk_label_new (_("\347\224\250\346\210\267\345\257\206\347\240\201:"));
  gtk_widget_show (label_passwd);
  gtk_table_attach (GTK_TABLE (table_login), label_passwd, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_passwd), 0, 0.5);

  comboboxentry_name = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_name);
  gtk_table_attach (GTK_TABLE (table_login), comboboxentry_name, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  comboboxentry_ip = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_ip);
  gtk_table_attach (GTK_TABLE (table_login), comboboxentry_ip, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (comboboxentry_ip, 216, -1);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table_login), hbox5, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  entry_passwd = gtk_entry_new ();
  gtk_widget_show (entry_passwd);
  gtk_box_pack_start (GTK_BOX (hbox5), entry_passwd, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry_passwd, 163, -1);
  gtk_entry_set_max_length (GTK_ENTRY (entry_passwd), 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_passwd), 9679);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_box_pack_start (GTK_BOX (hbox5), fixed5, TRUE, TRUE, 0);

  checkbutton_rem = gtk_check_button_new_with_mnemonic (_("\350\256\260\344\275\217\345\257\206\347\240\201\357\274\237"));
  gtk_widget_show (checkbutton_rem);
  gtk_box_pack_start (GTK_BOX (vbox_login), checkbutton_rem, FALSE, FALSE, 0);
  gtk_widget_set_size_request (checkbutton_rem, -1, 29);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_rem), 3);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox_login), hbox2, TRUE, TRUE, 0);

  button_help = gtk_button_new ();
  gtk_widget_show (button_help);
  gtk_box_pack_start (GTK_BOX (hbox2), button_help, FALSE, FALSE, 0);
  gtk_widget_set_size_request (button_help, 70, -1);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_help), alignment8);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox6);

  image324 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image324);
  gtk_box_pack_start (GTK_BOX (hbox6), image324, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("\345\270\256\345\212\251"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (hbox2), fixed4, TRUE, TRUE, 0);

  button_cancel = gtk_button_new ();
  gtk_widget_show (button_cancel);
  gtk_box_pack_start (GTK_BOX (hbox2), button_cancel, FALSE, FALSE, 0);
  gtk_widget_set_size_request (button_cancel, 70, -1);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_cancel), alignment6);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox3);

  image322 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image322);
  gtk_box_pack_start (GTK_BOX (hbox3), image322, FALSE, FALSE, 0);

  label_cancel = gtk_label_new_with_mnemonic (_("\345\217\226\346\266\210"));
  gtk_widget_show (label_cancel);
  gtk_box_pack_start (GTK_BOX (hbox3), label_cancel, FALSE, FALSE, 0);

  button_ok = gtk_button_new ();
  gtk_widget_show (button_ok);
  gtk_box_pack_start (GTK_BOX (hbox2), button_ok, FALSE, FALSE, 0);
  gtk_widget_set_size_request (button_ok, 70, -1);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_ok), alignment7);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox4);

  image323 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image323);
  gtk_box_pack_start (GTK_BOX (hbox4), image323, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("\347\241\256\345\256\232"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window_login, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_rem, "toggled",
                    G_CALLBACK (cb_login_rem_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_help, "clicked",
                    G_CALLBACK (cb_login_help_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cancel, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button_ok, "clicked",
                    G_CALLBACK (cb_login_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_login, window_login, "window_login");
  GLADE_HOOKUP_OBJECT (window_login, vbox_login, "vbox_login");
  GLADE_HOOKUP_OBJECT (window_login, image_login, "image_login");
  GLADE_HOOKUP_OBJECT (window_login, table_login, "table_login");
  GLADE_HOOKUP_OBJECT (window_login, label_ip, "label_ip");
  GLADE_HOOKUP_OBJECT (window_login, label_name, "label_name");
  GLADE_HOOKUP_OBJECT (window_login, label_passwd, "label_passwd");
  GLADE_HOOKUP_OBJECT (window_login, comboboxentry_name, "comboboxentry_name");
  GLADE_HOOKUP_OBJECT (window_login, comboboxentry_ip, "comboboxentry_ip");
  GLADE_HOOKUP_OBJECT (window_login, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_login, entry_passwd, "entry_passwd");
  GLADE_HOOKUP_OBJECT (window_login, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_login, checkbutton_rem, "checkbutton_rem");
  GLADE_HOOKUP_OBJECT (window_login, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_login, button_help, "button_help");
  GLADE_HOOKUP_OBJECT (window_login, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_login, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_login, image324, "image324");
  GLADE_HOOKUP_OBJECT (window_login, label6, "label6");
  GLADE_HOOKUP_OBJECT (window_login, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_login, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT (window_login, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_login, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_login, image322, "image322");
  GLADE_HOOKUP_OBJECT (window_login, label_cancel, "label_cancel");
  GLADE_HOOKUP_OBJECT (window_login, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (window_login, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_login, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_login, image323, "image323");
  GLADE_HOOKUP_OBJECT (window_login, label5, "label5");

  return window_login;
}

