/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_main (void)
{
  GtkWidget *window_main;
  GtkWidget *vbox_main;
  GtkWidget *menubar;
  GtkWidget *menubar_file;
  GtkWidget *menubar_file_menu;
  GtkWidget *login;
  GtkWidget *image82;
  GtkWidget *logout;
  GtkWidget *image83;
  GtkWidget *file_separator_one;
  GtkWidget *restart;
  GtkWidget *image84;
  GtkWidget *shutdown;
  GtkWidget *image85;
  GtkWidget *file_separator_two;
  GtkWidget *quit;
  GtkWidget *image86;
  GtkWidget *menubar_edit;
  GtkWidget *menubar_edit_menu;
  GtkWidget *edit_upload;
  GtkWidget *image87;
  GtkWidget *edit_separator_one;
  GtkWidget *edit_downolad;
  GtkWidget *image88;
  GtkWidget *menubar_help;
  GtkWidget *menubar_help_menu;
  GtkWidget *help_topic;
  GtkWidget *image89;
  GtkWidget *help_separator_one;
  GtkWidget *help_about;
  GtkWidget *image90;
  GtkWidget *toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolitem_back;
  GtkWidget *button_back;
  GtkWidget *alignment2;
  GtkWidget *vbox_tool_back;
  GtkWidget *image_back;
  GtkWidget *label_back;
  GtkWidget *toolitem_up;
  GtkWidget *button_up;
  GtkWidget *alignment3;
  GtkWidget *vbox_tool_up;
  GtkWidget *image_up;
  GtkWidget *label_up;
  GtkWidget *toolitem_tool;
  GtkWidget *vseparator_tool;
  GtkWidget *toolitem_downolad;
  GtkWidget *button_download;
  GtkWidget *alignment4;
  GtkWidget *vbox_tool_download;
  GtkWidget *image_download;
  GtkWidget *label_download;
  GtkWidget *toolitem_upload;
  GtkWidget *button_upload;
  GtkWidget *alignment5;
  GtkWidget *vbox8;
  GtkWidget *image_upload;
  GtkWidget *label_upload;
  GtkWidget *notebook_main;
  GtkWidget *hbox_notebook;
  GtkWidget *image1;
  GtkWidget *vbox9;
  GtkWidget *label_hostname;
  GtkWidget *label_release;
  GtkWidget *label_kernel;
  GtkWidget *label_memory;
  GtkWidget *label_cpuinfo;
  GtkWidget *label_cpuused;
  GtkWidget *label_cpuload;
  GtkWidget *label_ssinfo;
  GtkWidget *scrolledwindow2;
  GtkWidget *clist1;
  GtkWidget *label_name;
  GtkWidget *label_pid;
  GtkWidget *label_status;
  GtkWidget *label_cpu;
  GtkWidget *label_mem;
  GtkWidget *label_sprocess;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview_fview;
  GtkWidget *label_fview;
  GtkWidget *frame_main;
  GtkWidget *vbox2;
  GtkWidget *frame2;
  GtkWidget *alignment1;
  GtkWidget *vbox3;
  GtkWidget *vbox4;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview1;
  GtkWidget *hbox2;
  GtkWidget *entry1;
  GtkWidget *label4;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_main), _("Linux ARMS(hostclient)"));
  gtk_window_set_default_size (GTK_WINDOW (window_main), 800, 600);

  vbox_main = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_main);
  gtk_container_add (GTK_CONTAINER (window_main), vbox_main);

  menubar = gtk_menu_bar_new ();
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox_main), menubar, FALSE, FALSE, 0);

  menubar_file = gtk_menu_item_new_with_mnemonic (_("\346\226\207\344\273\266(_F)"));
  gtk_widget_show (menubar_file);
  gtk_container_add (GTK_CONTAINER (menubar), menubar_file);

  menubar_file_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_file), menubar_file_menu);

  login = gtk_image_menu_item_new_with_mnemonic (_("\347\231\273\345\275\225"));
  gtk_widget_show (login);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), login);
  gtk_tooltips_set_tip (tooltips, login, _("\347\231\273\345\275\225arm\347\263\273\347\273\237"), NULL);

  image82 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image82);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (login), image82);

  logout = gtk_image_menu_item_new_with_mnemonic (_("\346\263\250\351\224\200"));
  gtk_widget_show (logout);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), logout);
  gtk_tooltips_set_tip (tooltips, logout, _("\346\263\250\351\224\200\345\275\223\345\211\215\347\224\250\346\210\267"), NULL);

  image83 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image83);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (logout), image83);

  file_separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (file_separator_one);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), file_separator_one);
  gtk_widget_set_sensitive (file_separator_one, FALSE);

  restart = gtk_image_menu_item_new_with_mnemonic (_("\351\207\215\345\220\257"));
  gtk_widget_show (restart);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), restart);
  gtk_widget_add_accelerator (restart, "activate", accel_group,
                              GDK_R, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image84 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image84);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (restart), image84);

  shutdown = gtk_image_menu_item_new_with_mnemonic (_("\345\205\263\346\234\272"));
  gtk_widget_show (shutdown);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), shutdown);
  gtk_tooltips_set_tip (tooltips, shutdown, _("\345\205\263\351\227\255arm\347\263\273\347\273\237"), NULL);

  image85 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image85);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (shutdown), image85);

  file_separator_two = gtk_separator_menu_item_new ();
  gtk_widget_show (file_separator_two);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), file_separator_two);
  gtk_widget_set_sensitive (file_separator_two, FALSE);

  quit = gtk_image_menu_item_new_with_mnemonic (_("\351\200\200\345\207\272"));
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (menubar_file_menu), quit);
  gtk_widget_add_accelerator (quit, "activate", accel_group,
                              GDK_Q, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image86 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image86);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit), image86);

  menubar_edit = gtk_menu_item_new_with_mnemonic (_("\347\274\226\350\276\221(_E)"));
  gtk_widget_show (menubar_edit);
  gtk_container_add (GTK_CONTAINER (menubar), menubar_edit);

  menubar_edit_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_edit), menubar_edit_menu);

  edit_upload = gtk_image_menu_item_new_with_mnemonic (_("\344\270\212\344\274\240"));
  gtk_widget_show (edit_upload);
  gtk_container_add (GTK_CONTAINER (menubar_edit_menu), edit_upload);
  gtk_tooltips_set_tip (tooltips, edit_upload, _("\344\273\216arm\347\263\273\347\273\237\344\270\212\344\274\240\346\226\207\344\273\266\345\210\260\346\234\254\346\234\272"), NULL);
  gtk_widget_add_accelerator (edit_upload, "activate", accel_group,
                              GDK_U, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image87 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image87);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (edit_upload), image87);

  edit_separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (edit_separator_one);
  gtk_container_add (GTK_CONTAINER (menubar_edit_menu), edit_separator_one);
  gtk_widget_set_sensitive (edit_separator_one, FALSE);

  edit_downolad = gtk_image_menu_item_new_with_mnemonic (_("\344\270\213\350\275\275"));
  gtk_widget_show (edit_downolad);
  gtk_container_add (GTK_CONTAINER (menubar_edit_menu), edit_downolad);
  gtk_tooltips_set_tip (tooltips, edit_downolad, _("\344\273\216\346\234\254\346\234\272\344\270\213\350\275\275\346\226\207\344\273\266\345\210\260arm\347\263\273\347\273\237\344\270\212"), NULL);
  gtk_widget_add_accelerator (edit_downolad, "activate", accel_group,
                              GDK_D, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image88 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image88);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (edit_downolad), image88);

  menubar_help = gtk_menu_item_new_with_mnemonic (_("\345\270\256\345\212\251(_H)"));
  gtk_widget_show (menubar_help);
  gtk_container_add (GTK_CONTAINER (menubar), menubar_help);

  menubar_help_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar_help), menubar_help_menu);

  help_topic = gtk_image_menu_item_new_with_mnemonic (_("\345\270\256\345\212\251\344\270\273\351\242\230"));
  gtk_widget_show (help_topic);
  gtk_container_add (GTK_CONTAINER (menubar_help_menu), help_topic);
  gtk_tooltips_set_tip (tooltips, help_topic, _("\345\270\256\345\212\251\346\226\207\346\241\243"), NULL);
  gtk_widget_add_accelerator (help_topic, "activate", accel_group,
                              GDK_F1, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image89 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image89);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (help_topic), image89);

  help_separator_one = gtk_separator_menu_item_new ();
  gtk_widget_show (help_separator_one);
  gtk_container_add (GTK_CONTAINER (menubar_help_menu), help_separator_one);
  gtk_widget_set_sensitive (help_separator_one, FALSE);

  help_about = gtk_image_menu_item_new_with_mnemonic (_("\345\205\263\344\272\216"));
  gtk_widget_show (help_about);
  gtk_container_add (GTK_CONTAINER (menubar_help_menu), help_about);
  gtk_tooltips_set_tip (tooltips, help_about, _("\345\205\263\344\272\216\346\234\254\350\275\257\344\273\266"), NULL);
  gtk_widget_add_accelerator (help_about, "activate", accel_group,
                              GDK_A, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image90 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image90);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (help_about), image90);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gtk_box_pack_start (GTK_BOX (vbox_main), toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar));

  toolitem_back = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_back);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_back);

  button_back = gtk_button_new ();
  gtk_widget_show (button_back);
  gtk_container_add (GTK_CONTAINER (toolitem_back), button_back);
  gtk_widget_set_size_request (button_back, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_back, _("\350\277\224\345\233\236\345\210\260\345\210\232\346\211\215\350\256\277\351\227\256\350\277\207\347\232\204\347\233\256\345\275\225"), NULL);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_back), alignment2);

  vbox_tool_back = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_tool_back);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox_tool_back);

  image_back = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_back);
  gtk_box_pack_start (GTK_BOX (vbox_tool_back), image_back, TRUE, TRUE, 0);

  label_back = gtk_label_new (_("\345\220\216\351\200\200"));
  gtk_widget_show (label_back);
  gtk_box_pack_start (GTK_BOX (vbox_tool_back), label_back, FALSE, FALSE, 0);

  toolitem_up = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_up);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_up);

  button_up = gtk_button_new ();
  gtk_widget_show (button_up);
  gtk_container_add (GTK_CONTAINER (toolitem_up), button_up);
  gtk_widget_set_size_request (button_up, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_up, _("\350\277\224\345\233\236\344\270\212\347\272\247\347\233\256\345\275\225"), NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_up), alignment3);

  vbox_tool_up = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_tool_up);
  gtk_container_add (GTK_CONTAINER (alignment3), vbox_tool_up);

  image_up = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_up);
  gtk_box_pack_start (GTK_BOX (vbox_tool_up), image_up, TRUE, TRUE, 0);

  label_up = gtk_label_new (_("\345\220\221\344\270\212"));
  gtk_widget_show (label_up);
  gtk_box_pack_start (GTK_BOX (vbox_tool_up), label_up, FALSE, FALSE, 0);

  toolitem_tool = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_tool);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_tool);

  vseparator_tool = gtk_vseparator_new ();
  gtk_widget_show (vseparator_tool);
  gtk_container_add (GTK_CONTAINER (toolitem_tool), vseparator_tool);
  gtk_widget_set_size_request (vseparator_tool, 5, -1);

  toolitem_downolad = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_downolad);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_downolad);

  button_download = gtk_button_new ();
  gtk_widget_show (button_download);
  gtk_container_add (GTK_CONTAINER (toolitem_downolad), button_download);
  gtk_widget_set_size_request (button_download, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_download, _("\344\273\216\346\234\254\346\234\272\344\270\213\350\275\275\346\226\207\344\273\266\345\210\260arm\347\263\273\347\273\237\344\270\212"), NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_download), alignment4);

  vbox_tool_download = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_tool_download);
  gtk_container_add (GTK_CONTAINER (alignment4), vbox_tool_download);

  image_download = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_download);
  gtk_box_pack_start (GTK_BOX (vbox_tool_download), image_download, TRUE, TRUE, 0);

  label_download = gtk_label_new (_("\344\270\213\350\275\275"));
  gtk_widget_show (label_download);
  gtk_box_pack_start (GTK_BOX (vbox_tool_download), label_download, FALSE, FALSE, 0);

  toolitem_upload = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem_upload);
  gtk_container_add (GTK_CONTAINER (toolbar), toolitem_upload);

  button_upload = gtk_button_new ();
  gtk_widget_show (button_upload);
  gtk_container_add (GTK_CONTAINER (toolitem_upload), button_upload);
  gtk_widget_set_size_request (button_upload, 60, -1);
  gtk_tooltips_set_tip (tooltips, button_upload, _("\344\273\216arm\347\263\273\347\273\237\344\270\212\344\274\240\346\226\207\344\273\266\345\210\260\346\234\254\346\234\272\344\270\212"), NULL);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_upload), alignment5);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (alignment5), vbox8);

  image_upload = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_upload);
  gtk_box_pack_start (GTK_BOX (vbox8), image_upload, TRUE, TRUE, 0);

  label_upload = gtk_label_new (_("\344\270\212\344\274\240"));
  gtk_widget_show (label_upload);
  gtk_box_pack_start (GTK_BOX (vbox8), label_upload, FALSE, FALSE, 0);

  notebook_main = gtk_notebook_new ();
  gtk_widget_show (notebook_main);
  gtk_box_pack_start (GTK_BOX (vbox_main), notebook_main, TRUE, TRUE, 0);
  gtk_widget_set_size_request (notebook_main, -1, 425);

  hbox_notebook = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_notebook);
  gtk_container_add (GTK_CONTAINER (notebook_main), hbox_notebook);

  image1 = create_pixmap (window_main, NULL);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox_notebook), image1, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox_notebook), vbox9, TRUE, TRUE, 0);

  label_hostname = gtk_label_new (Q_("\344\270\273\346\234\272\345\220\215"));
  gtk_widget_show (label_hostname);
  gtk_box_pack_start (GTK_BOX (vbox9), label_hostname, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_hostname), 0, 0.5);

  label_release = gtk_label_new (_("\345\217\221\350\241\214\347\211\210\346\234\254"));
  gtk_widget_show (label_release);
  gtk_box_pack_start (GTK_BOX (vbox9), label_release, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_release), 0, 0.5);

  label_kernel = gtk_label_new (_("\345\206\205\346\240\270\347\211\210\346\234\254"));
  gtk_widget_show (label_kernel);
  gtk_box_pack_start (GTK_BOX (vbox9), label_kernel, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_kernel), 0, 0.5);

  label_memory = gtk_label_new (_("\345\206\205\345\255\230\357\274\232\357\274\210\345\212\250\346\200\201\345\217\230\345\214\226\357\274\211"));
  gtk_widget_show (label_memory);
  gtk_box_pack_start (GTK_BOX (vbox9), label_memory, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_memory), 0, 0.5);

  label_cpuinfo = gtk_label_new (_("CPU\345\236\213\345\217\267"));
  gtk_widget_show (label_cpuinfo);
  gtk_box_pack_start (GTK_BOX (vbox9), label_cpuinfo, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_cpuinfo), 0, 0.5);

  label_cpuused = gtk_label_new (_("\344\270\273\351\242\221\345\222\214\344\275\277\347\224\250\347\216\207"));
  gtk_widget_show (label_cpuused);
  gtk_box_pack_start (GTK_BOX (vbox9), label_cpuused, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_cpuused), 0, 0.5);

  label_cpuload = gtk_label_new (_("CPU\350\264\237\350\275\275"));
  gtk_widget_show (label_cpuload);
  gtk_box_pack_start (GTK_BOX (vbox9), label_cpuload, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_cpuload), 0, 0.5);

  label_ssinfo = gtk_label_new (_("\347\263\273\347\273\237\344\277\241\346\201\257"));
  gtk_widget_show (label_ssinfo);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_main), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_main), 0), label_ssinfo);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook_main), scrolledwindow2);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  clist1 = gtk_clist_new (5);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label_name = gtk_label_new (_("\350\277\233\347\250\213\345\220\215"));
  gtk_widget_show (label_name);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label_name);

  label_pid = gtk_label_new (_("\350\277\233\347\250\213\345\217\267"));
  gtk_widget_show (label_pid);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label_pid);

  label_status = gtk_label_new (_("\350\277\233\347\250\213\347\212\266\346\200\201"));
  gtk_widget_show (label_status);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label_status);

  label_cpu = gtk_label_new (_("CPU\344\275\277\347\224\250\347\216\207"));
  gtk_widget_show (label_cpu);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label_cpu);

  label_mem = gtk_label_new (_("\345\206\205\345\255\230\344\275\277\347\224\250\351\207\217"));
  gtk_widget_show (label_mem);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label_mem);

  label_sprocess = gtk_label_new (_("\347\263\273\347\273\237\350\277\233\347\250\213"));
  gtk_widget_show (label_sprocess);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_main), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_main), 1), label_sprocess);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook_main), scrolledwindow3);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  treeview_fview = gtk_tree_view_new ();
  gtk_widget_show (treeview_fview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview_fview);

  label_fview = gtk_label_new (_("\346\265\217\350\247\210\346\226\207\344\273\266"));
  gtk_widget_show (label_fview);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_main), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_main), 2), label_fview);

  frame_main = gtk_frame_new (NULL);
  gtk_widget_show (frame_main);
  gtk_box_pack_start (GTK_BOX (vbox_main), frame_main, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_main), GTK_SHADOW_NONE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame_main), vbox2);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox2), frame2, FALSE, FALSE, 0);
  gtk_widget_set_size_request (frame2, -1, 221);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame2), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox3);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox4, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview1);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox2), entry1, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("niutaasfsdf$"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 9679);

  label4 = gtk_label_new (_("\345\256\236\346\227\266\346\216\247\345\210\266"));
  gtk_widget_show (label4);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label4);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox_main), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window_main, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) login, "activate",
                    G_CALLBACK (cb_login_activate),
                    NULL);
  g_signal_connect ((gpointer) logout, "activate",
                    G_CALLBACK (cb_logout_activate),
                    NULL);
  g_signal_connect ((gpointer) restart, "activate",
                    G_CALLBACK (cb_restart_activate),
                    NULL);
  g_signal_connect ((gpointer) shutdown, "activate",
                    G_CALLBACK (cb_shutdown_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) edit_upload, "activate",
                    G_CALLBACK (cb_edit_upload_activate),
                    NULL);
  g_signal_connect ((gpointer) edit_downolad, "activate",
                    G_CALLBACK (cb_edit_downolad_activate),
                    NULL);
  g_signal_connect ((gpointer) help_topic, "activate",
                    G_CALLBACK (cb_help_topic_activate),
                    NULL);
  g_signal_connect ((gpointer) help_about, "activate",
                    G_CALLBACK (cb_help_about_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_main, window_main, "window_main");
  GLADE_HOOKUP_OBJECT (window_main, vbox_main, "vbox_main");
  GLADE_HOOKUP_OBJECT (window_main, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (window_main, menubar_file, "menubar_file");
  GLADE_HOOKUP_OBJECT (window_main, menubar_file_menu, "menubar_file_menu");
  GLADE_HOOKUP_OBJECT (window_main, login, "login");
  GLADE_HOOKUP_OBJECT (window_main, image82, "image82");
  GLADE_HOOKUP_OBJECT (window_main, logout, "logout");
  GLADE_HOOKUP_OBJECT (window_main, image83, "image83");
  GLADE_HOOKUP_OBJECT (window_main, file_separator_one, "file_separator_one");
  GLADE_HOOKUP_OBJECT (window_main, restart, "restart");
  GLADE_HOOKUP_OBJECT (window_main, image84, "image84");
  GLADE_HOOKUP_OBJECT (window_main, shutdown, "shutdown");
  GLADE_HOOKUP_OBJECT (window_main, image85, "image85");
  GLADE_HOOKUP_OBJECT (window_main, file_separator_two, "file_separator_two");
  GLADE_HOOKUP_OBJECT (window_main, quit, "quit");
  GLADE_HOOKUP_OBJECT (window_main, image86, "image86");
  GLADE_HOOKUP_OBJECT (window_main, menubar_edit, "menubar_edit");
  GLADE_HOOKUP_OBJECT (window_main, menubar_edit_menu, "menubar_edit_menu");
  GLADE_HOOKUP_OBJECT (window_main, edit_upload, "edit_upload");
  GLADE_HOOKUP_OBJECT (window_main, image87, "image87");
  GLADE_HOOKUP_OBJECT (window_main, edit_separator_one, "edit_separator_one");
  GLADE_HOOKUP_OBJECT (window_main, edit_downolad, "edit_downolad");
  GLADE_HOOKUP_OBJECT (window_main, image88, "image88");
  GLADE_HOOKUP_OBJECT (window_main, menubar_help, "menubar_help");
  GLADE_HOOKUP_OBJECT (window_main, menubar_help_menu, "menubar_help_menu");
  GLADE_HOOKUP_OBJECT (window_main, help_topic, "help_topic");
  GLADE_HOOKUP_OBJECT (window_main, image89, "image89");
  GLADE_HOOKUP_OBJECT (window_main, help_separator_one, "help_separator_one");
  GLADE_HOOKUP_OBJECT (window_main, help_about, "help_about");
  GLADE_HOOKUP_OBJECT (window_main, image90, "image90");
  GLADE_HOOKUP_OBJECT (window_main, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_back, "toolitem_back");
  GLADE_HOOKUP_OBJECT (window_main, button_back, "button_back");
  GLADE_HOOKUP_OBJECT (window_main, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_main, vbox_tool_back, "vbox_tool_back");
  GLADE_HOOKUP_OBJECT (window_main, image_back, "image_back");
  GLADE_HOOKUP_OBJECT (window_main, label_back, "label_back");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_up, "toolitem_up");
  GLADE_HOOKUP_OBJECT (window_main, button_up, "button_up");
  GLADE_HOOKUP_OBJECT (window_main, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_main, vbox_tool_up, "vbox_tool_up");
  GLADE_HOOKUP_OBJECT (window_main, image_up, "image_up");
  GLADE_HOOKUP_OBJECT (window_main, label_up, "label_up");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_tool, "toolitem_tool");
  GLADE_HOOKUP_OBJECT (window_main, vseparator_tool, "vseparator_tool");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_downolad, "toolitem_downolad");
  GLADE_HOOKUP_OBJECT (window_main, button_download, "button_download");
  GLADE_HOOKUP_OBJECT (window_main, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_main, vbox_tool_download, "vbox_tool_download");
  GLADE_HOOKUP_OBJECT (window_main, image_download, "image_download");
  GLADE_HOOKUP_OBJECT (window_main, label_download, "label_download");
  GLADE_HOOKUP_OBJECT (window_main, toolitem_upload, "toolitem_upload");
  GLADE_HOOKUP_OBJECT (window_main, button_upload, "button_upload");
  GLADE_HOOKUP_OBJECT (window_main, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_main, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (window_main, image_upload, "image_upload");
  GLADE_HOOKUP_OBJECT (window_main, label_upload, "label_upload");
  GLADE_HOOKUP_OBJECT (window_main, notebook_main, "notebook_main");
  GLADE_HOOKUP_OBJECT (window_main, hbox_notebook, "hbox_notebook");
  GLADE_HOOKUP_OBJECT (window_main, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_main, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (window_main, label_hostname, "label_hostname");
  GLADE_HOOKUP_OBJECT (window_main, label_release, "label_release");
  GLADE_HOOKUP_OBJECT (window_main, label_kernel, "label_kernel");
  GLADE_HOOKUP_OBJECT (window_main, label_memory, "label_memory");
  GLADE_HOOKUP_OBJECT (window_main, label_cpuinfo, "label_cpuinfo");
  GLADE_HOOKUP_OBJECT (window_main, label_cpuused, "label_cpuused");
  GLADE_HOOKUP_OBJECT (window_main, label_cpuload, "label_cpuload");
  GLADE_HOOKUP_OBJECT (window_main, label_ssinfo, "label_ssinfo");
  GLADE_HOOKUP_OBJECT (window_main, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window_main, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (window_main, label_name, "label_name");
  GLADE_HOOKUP_OBJECT (window_main, label_pid, "label_pid");
  GLADE_HOOKUP_OBJECT (window_main, label_status, "label_status");
  GLADE_HOOKUP_OBJECT (window_main, label_cpu, "label_cpu");
  GLADE_HOOKUP_OBJECT (window_main, label_mem, "label_mem");
  GLADE_HOOKUP_OBJECT (window_main, label_sprocess, "label_sprocess");
  GLADE_HOOKUP_OBJECT (window_main, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window_main, treeview_fview, "treeview_fview");
  GLADE_HOOKUP_OBJECT (window_main, label_fview, "label_fview");
  GLADE_HOOKUP_OBJECT (window_main, frame_main, "frame_main");
  GLADE_HOOKUP_OBJECT (window_main, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window_main, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (window_main, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_main, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window_main, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window_main, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window_main, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window_main, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_main, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window_main, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_main, statusbar, "statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (window_main, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (window_main), accel_group);

  return window_main;
}

