/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_main (void);
GtkWidget* create_popup_menu_process (void);
GtkWidget* create_popup_menu_fview (void);
GtkWidget* create_window_login (void);
